# Use Node image
FROM node:20.12.0-alpine3.19

# Set working directory inside the container
WORKDIR /src/app

# Install pnpm globally
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy necessary project files
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

# Copy monorepo packages and apps
COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN pnpm install

# Build only the `web` using turbo
RUN pnpm turbo run build --filter=web...

# Start the web app
CMD ["pnpm", "run", "start-web"]
